image: debian/stable
packages:
    - wget
sources:
    - https://github.com/peterbourgon/fastly-exporter
tasks:
    - go_toolchain: |
        go_version="$(wget -q -O- https://golang.org/VERSION?m=text)"
        wget -q https://dl.google.com/go/$go_version.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf $go_version.linux-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/go /usr/bin/go
        go env
    - dependencies: |
        mkdir -p $HOME/go/src/github.com/peterbourgon
        mv fastly-exporter $HOME/go/src/github.com/peterbourgon
        go get -t github.com/peterbourgon/fastly-exporter/...
    - test: |
        go test -race -v github.com/peterbourgon/fastly-exporter/...
