version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./compose/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    links:
      - fastly-exporter:fastly-exporter
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./compose/grafana/grafana_data:/var/lib/grafana
      - ./compose/grafana/provisioning/:/etc/grafana/provisioning/

  fastly-exporter:
    image: mrnetops/fastly-exporter
    command: -token ${FASTLY_API_TOKEN}
    expose:
      - 8080
    ports:
     - 8080:8080

