{
 "title": "Fastly Insights",
 "tags": [ "Fastly" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(fastly_rt_requests_total, service_name)"
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": "label_values(fastly_rt_requests_total, service_id)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(fastly_rt_requests_total, datacenter)"
   },
   { "name": "rate", "label": "Rate", "query": "30s" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fastly_rt_status_code_total{status_code=~\"5..\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (datacenter)"
    }
   ]
  },
  {
   "title": "Non-200 response codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fastly_rt_status_code_total{status_code!~\"200\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (status_code)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id)/ (sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id)\n+ sum(rate(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id))"
    }
   ]
  },
  {
   "title": "5xx Response Codes",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(fastly_rt_status_code_total{status_code=~\"5..\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id)/ (sum(increase(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id)\n+ sum(increase(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id))\n",
     "legendFormat": "{{service_id}}"
    }
   ]
  },
  {
   "title": "Non-200 response codes",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(fastly_rt_status_code_total{status_code!~\"200\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Top 10 Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(10, sum(increase(fastly_rt_status_code_total{status_code!~\"200\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id, service_name, status_code))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "topk(10, sum(increase(fastly_rt_status_code_total{status_code=~\"501|502|503|504|505\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (service_id, datacenter, service_name, status_code))"
    }
   ]
  }
 ]
}