on: push
name: Test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: golint (revive)
        run: |
          go install github.com/mgechev/revive@v1.0.9
          test -z "$(revive ./... 2>&1)"
      - name: go vet
        run: go vet ./...
      - name: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2020.2.1
          staticcheck ./...
      - name: gofumpt
        if: matrix.platform != 'windows-latest' # :(
        run: |
          go install mvdan.cc/gofumpt@v0.1.1
          test -z "$(gofumpt -s -l -d -e . 2>&1)"
      - name: go test
        run: go test -race ./...
